const props = {
  user: {
    signingIn: false,
    showSignUp: false,
    registering: false,
    showUserForm: false,
    submittingUser: false,
  },
  galaxy: {
    storesMap: {},
    loginUser: {
      name: 'Haidi L.',
      full_name: 'Haidi Liu',
      id: 102301,
      access_token: '6ip641gfc85ui0jsz474t9abxd8ihhy',
      email: 'haidi.liu@bindo.com',
      is_inventory_manager: false,
      is_admin: false,
      is_staff: true,
      belongs_to_internal: true,
      belongs_to_reseller: false,
      belongs_to_courier: false,
      user_type: 0,
    },
    storesIDRefSlug: {},
    storesSlugRefID: {},
    storesAppsMap: {},
    openMenuKeys: ['7312_966373984008438784'],
    roleModule: {
      id: '996023641407784960',
      appID: '974831517006070784',
      name: 'Store Roles',
      alias: 'store_roles',
      tableInfo: {
        database: 'bindo',
        tableName: 'store_roles',
      },
      crossChain: true,
      queryConditions: null,
      template: {
        form: [
          {
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: '',
            title: 'integerNumber',
            uuid: '72d1985049f311e9b0aef9194c6304f1',
            viewType: 'INTEGER_NUMBER',
          },
          {
            addonAfter: [],
            addonBefore: [],
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: 'Role Name ...',
            title: 'text',
            uuid: '507de7e049f311e9b0aef9194c6304f1',
            viewType: 'TEXT',
          },
          {
            addonAfter: [],
            addonBefore: [],
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: '',
            title: 'text',
            uuid: '25953a00512411e9872e5721d04b90c3',
            viewType: 'TEXT',
          },
          {
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: '',
            title: 'boolean',
            uuid: 'e0d88e8049f311e9a249fb04ceb000c5',
            viewType: 'BOOLEAN',
          },
        ],
        funcBtns: {
          form: [
            {
              icon: 'icon-view',
              iconType: 'bindo',
              params: {},
              scriptName: 'View',
              status: 'ACTIVE',
              title: 'common:editor.view',
              type: 'DEFAULT',
              uuid: '2a801b3049f311e9b0aef9194c6304f1',
            },
            {
              icon: 'icon-edit',
              iconType: 'bindo',
              params: {},
              scriptName: 'Edit',
              status: 'ACTIVE',
              title: 'common:editor.edit',
              type: 'DEFAULT',
              uuid: '2a801b3149f311e9b0aef9194c6304f1',
            },
            {
              icon: 'icon-delete',
              iconType: 'bindo',
              params: {},
              scriptName: 'Delete',
              status: 'ACTIVE',
              title: 'common:editor.delete',
              type: 'DEFAULT',
              uuid: '2a801b3249f311e9b0aef9194c6304f1',
            },
          ],
          list: [
            {
              icon: '',
              iconType: '',
              params: {},
              scriptName: 'New',
              status: 'ACTIVE',
              title: 'common:editor.new',
              type: 'DEFAULT',
              uuid: '2a801b3349f311e9b0aef9194c6304f1',
            },
            {
              icon: '',
              iconType: '',
              params: {},
              scriptName: 'Import',
              status: 'ACTIVE',
              title: 'common:editor.import',
              type: 'DEFAULT',
              uuid: '2a801b3449f311e9b0aef9194c6304f1',
            },
            {
              icon: '',
              iconType: '',
              params: {},
              scriptName: 'Export',
              status: 'ACTIVE',
              title: 'common:editor.export',
              type: 'DEFAULT',
              uuid: '2a801b3549f311e9b0aef9194c6304f1',
            },
          ],
        },
        list: [
          {
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: '',
            uuid: '507de7e049f311e9b0aef9194c6304f1',
            viewType: 'TEXT',
          },
          {
            helpTooltip: '',
            hiddenLabel: false,
            parentUuid: '0',
            placeholder: '',
            uuid: '25953a00512411e9872e5721d04b90c3',
            viewType: 'TEXT',
          },
          {
            parentUuid: '0',
            uuid: 'createdAt',
            viewType: 'DATE',
          },
          {
            parentUuid: '0',
            uuid: 'updatedAt',
            viewType: 'DATE',
          },
        ],
        viewsParams: {
          showSearch: true,
        },
      },
      storeID: 7306,
      fields: [
        {
          uuid: 'createdAt',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'Created At',
          name: 'created_at',
          type: 'BASIC',
          dataType: 'DATE',
          allowMultiValue: false,
          viewType: 'DATE',
          readOnly: true,
          invisible: true,
          installType: 'DEFAULT',
          required: false,
          isBindField: true,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: [],
          queryOrder: null,
          queryEvaluation: null,
          listens: [],
          validations: [],
          defaultValue: null,
          createdAt: '2019-03-19T03:00:36Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
        {
          uuid: 'updatedAt',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'Updated At',
          name: 'updated_at',
          type: 'BASIC',
          dataType: 'DATE',
          allowMultiValue: false,
          viewType: 'DATE',
          readOnly: true,
          invisible: true,
          installType: 'DEFAULT',
          required: false,
          isBindField: true,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: [],
          queryOrder: null,
          queryEvaluation: null,
          listens: [],
          validations: [],
          defaultValue: null,
          createdAt: '2019-03-19T03:00:36Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
        {
          uuid: '507de7e049f311e9b0aef9194c6304f1',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'Title',
          name: 'name',
          type: 'BASIC',
          dataType: 'TEXT',
          allowMultiValue: false,
          viewType: 'TEXT',
          readOnly: false,
          invisible: false,
          installType: 'DEFAULT',
          required: false,
          isBindField: true,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: [],
          queryOrder: null,
          queryEvaluation: null,
          listens: [],
          validations: [],
          defaultValue: null,
          createdAt: '2019-03-19T03:02:14Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
        {
          uuid: '72d1985049f311e9b0aef9194c6304f1',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'ID',
          name: 'id',
          type: 'BASIC',
          dataType: 'INTEGER_NUMBER',
          allowMultiValue: false,
          viewType: 'INTEGER_NUMBER',
          readOnly: false,
          invisible: true,
          installType: 'DEFAULT',
          required: false,
          isBindField: true,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: [],
          queryOrder: null,
          queryEvaluation: null,
          listens: [],
          validations: [],
          defaultValue: null,
          createdAt: '2019-03-19T03:02:47Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
        {
          uuid: 'e0d88e8049f311e9a249fb04ceb000c5',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'Is System',
          name: 'is_system',
          type: 'BASIC',
          dataType: 'BOOLEAN',
          allowMultiValue: false,
          viewType: 'BOOLEAN',
          readOnly: false,
          invisible: true,
          installType: 'DEFAULT',
          required: false,
          isBindField: false,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: null,
          queryOrder: null,
          queryEvaluation: null,
          listens: null,
          validations: null,
          defaultValue: null,
          createdAt: '2019-03-19T03:06:29Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
        {
          uuid: '25953a00512411e9872e5721d04b90c3',
          moduleID: '996023641407784960',
          storeID: 7306,
          label: 'Description',
          name: 'description',
          type: 'BASIC',
          dataType: 'TEXT',
          allowMultiValue: false,
          viewType: 'TEXT',
          readOnly: false,
          invisible: false,
          installType: 'DEFAULT',
          required: false,
          isBindField: false,
          i18n: {},
          allowValue: null,
          relation: null,
          link: null,
          queryConditions: null,
          queryOrder: null,
          queryEvaluation: null,
          listens: null,
          validations: null,
          defaultValue: null,
          createdAt: '2019-03-28T06:39:02Z',
          updatedAt: '2019-04-09T06:26:37Z',
          seqNoConfig: null,
        },
      ],
      moduleParentID: '0',
      createdAt: '2019-03-19T03:00:35Z',
      updatedAt: '2019-04-09T06:26:36Z',
      globalEnabled: true,
      uniqueIndexes: null,
    },
    storesAppsModulesMap: {},
    storesModulesPermissionsMap: {},
    storesRolesMap: {},
    bindoTablesMap: {},
    loadingContent: false,
    permissionsAndModulesDone: true,
    galaxyLoading: false,
    searchFilter: {},
    relationRecords: {},
  },
  module: {
    moduleEntity: {},
    selectedViewUuid: 'name',
    activeTab: 'view',
    viewType: 'form',
    existingModules: [],
    bindingTableFields: [],
  },
}

it('Conditional to MQL data', () => {
})
export default props
