export default {
  BUILDER: 'builder',
  DASHBOARD: 'dashboard',
  MODULE: 'module',
  EMBEDDED: 'embedded',
  SETTING: 'setting',
  WIKI_ONLY: 'wikiOnly',
  RECORDS: 'records',
  SUBMENU: 'subMenu',
  PERMISSION: 'permission',
  UPPERCASE_MODULE: 'MODULE',
  UPPERCASE_SETTING: 'SETTING',
  UPPERCASE_EMBEDDED: 'EMBEDDED',
  APP: 'APP',
  URL: 'url',
  TABLEAU: 'tableau',
  METABASE: 'metabase',
  METABASE_QUESTION: 'question',
  METABASE_DASHBOARD: 'dashboard',
  STORE: 'STORE',
  RELEASE: 'RELEASE',
  LIST: 'list',
  SCHEDULER: 'scheduler',
  FORM: 'form',
  SEARCH: 'search',
  ACTION: 'action',
  FILTER_RULES: 'filterRules',
  LINKAGE: 'linkage',
  DISPLAY: 'display',
  EDITABLE: 'editable',
  SQL: 'SQL',
  DEFAULTVALUE: 'DEFAULTVALUE',
  COLUMNVALUE: 'COLUMNVALUE',
  GREATERTHAN: 'GREATERTHAN',
  UNPUBLISHED: 'UNPUBLISHED',
  LESSTHAN: 'LESSTHAN',
  EQUAL: 'EQUAL',
  ISNULL: 'ISNULL',
  ISNOTNULL: 'ISNOTNULL',
  IN: 'IN',
  RADIO: 'radio',
  MULTIPLE: 'multiple',
  TAGS: 'tags',
  DATEPICKER: 'DatePicker',
  MONTHPICKER: 'MonthPicker',
  RANGEPICKER: 'RangePicker',
  WEEKPICKER: 'WeekPicker',
  STATIC: 'STATIC',
  DYNAMIC: 'DYNAMIC',

  BASIC: 'BASIC',
  RELATION: 'RELATION',
  LINK: 'LINK',
  PLAIN: 'PLAIN',
  AGGREGATE: 'AGGREGATE',

  INVISIBLE: 'INVISIBLE',
  READONLY: 'READONLY',
  REQUIRED: 'REQUIRED',
  VALUE: 'VALUE',
  FILTER: 'FILTER',
  IMAGE: 'IMAGE',

  CUSTOM_EVENT: 'CUSTOM_EVENT',
  CUSTOM: 'CUSTOM',
  DEFAULT: 'DEFAULT',

  CREATABLE: 'creatable',
  EXPORTABLE: 'exportable',
  IMPORTABLE: 'importable',
  DELETABLE: 'deletable',
  VIEWABLE: 'viewable',

  creatable: 'common:new',
  exportable: 'common:editor.export',
  importable: 'common:editor.import',
  deletable: 'common:delete',
  viewable: 'common:view',
  editable: 'common:edit',

  ENTERPRISE: 'ENTERPRISE',
  SYSTEM: 'SYSTEM',

  ACTIVE: 'ACTIVE',
  INVALID: 'INVALID',
  BIND_ACTION: 'bindAction',
  BIND_TEMPLATE: 'bindTemplate',

  NEW: 'New',
  VIEW: 'View',
  EDIT: 'edit',
  REMOVE: 'remove',
  INSERT: 'insert',

  MODULES: 'modules',
  FUNCTION: 'function',

  UNASSIGNED: '$null$',

  IMPORTERROR: 'IMPORTERROR',
  PENDING: 'PENDING',
  IMPORTED: 'IMPORTED',
  GLOBAL: 'Global',
  DONE: 'DONE',
  FAILED: 'FAILED',
  ROLE: 'ROLE',

  english: 'en-US',
  chinese: 'zh-CN',
  chineseHK: 'zh-HK',

  // 毫秒数
  ONE_HOUR: 3600000,
  ONE_DAY: 43200000,
  HALF_DAY: 21600000,
};
