export default {
  EQ: 'EQ',
  GT: 'GT',
  LT: 'LT',
  EGT: 'EGT',
  ELT: 'ELT',
  NOT_EQ: 'NOT',
  IN: 'IN',
  NOT_IN: 'NOT_IN',
  CONTAIN: 'CONTAIN',
  NOT_CONTAIN: 'NOT_CONTAIN',
  IS_NULL: 'IS_NULL',
  NOT_NULL: 'NOT_NULL',
  AND: 'AND',
  OR: 'OR',
  ADD: 'ADD',
  SUB: 'SUB',
  MULTI: 'MULTI',
  DIVISION: 'DIVISION',
}
