/* eslint-disable */
const storesRoute = '/:galaxyState/slugs/:storeSlugs';

export default {
	HOME:           			`/`,
	LOGIN:          			`/login`,
	PASSWORD_FORGOT:   		`/password/forgot`,
	PASSWORD_RECOVERY: 		`/password/recovery`,
	PASSWORD_RESET:    		`/password/reset`,
	DIRECTORY:      			`${storesRoute}`,
	WELCOME:        			`${storesRoute}/welcome`,
	APP_WELCOME:    			`${storesRoute}/apps/:appID/:slug/welcome`,
	APPS:           			`${storesRoute}/apps`,
	MENUS:      					`${storesRoute}/apps/:appID/:slug/menus`,
	MODELS:         			`${storesRoute}/models`,
	MODEL_FIELDS:   			`${storesRoute}/models/:moduleID/attributes/:slug`,
	MODULES:        			`${storesRoute}/modules`,
	EMBEDDED:      				`${storesRoute}/:appID/:slug/:menuID/embedded`,
	EMBEDDED_EDIT:  			`${storesRoute}/:appID/:slug/:menuID/embedded/edit`,
	WIKI_ONLY:      			`${storesRoute}/:appID/:slug/:menuID/wikionly`,
	WIKI_ONLY_EDIT:  			`${storesRoute}/:appID/:slug/:menuID/wikionly/edit`,
	RECORDS:       				`${storesRoute}/:appID/:slug/:menuID/:moduleID/records`,
	SCHEDULER:       			`${storesRoute}/:appID/:slug/:menuID/:moduleID/scheduler`,
	RECORD:         			`${storesRoute}/:appID/:slug/:menuID/:moduleID/record/:action`,
	RECORD_ACTION:  			`${storesRoute}/:appID/:slug/:menuID/:moduleID/record/:action/:recordID`,
	SETTINGS:       			`${storesRoute}/:appID/:slug/:menuID/:moduleID/settings`,
	PERMISSIONS:    			`${storesRoute}/:appID/:slug/:menuID/:moduleID/:from/permissions`,
	VIEWS:         		 		`${storesRoute}/:appID/:slug/:menuID/:moduleID/views`,
	FORM_VIEW:      			`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/form`,
	LIST_VIEW:      			`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/list`,
	SCHEDULER_VIEW:      	`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/scheduler`,
	MODULE_VIEWS:   			`${storesRoute}/:appID/:slug/:moduleID/views/:moduleName`,
	MODULE_FORM_VIEW:   	`${storesRoute}/:appID/:slug/:moduleID/views/form/:moduleName`,
	MODULE_LIST_VIEW:   	`${storesRoute}/:appID/:slug/:moduleID/views/list/:moduleName`,
	ACTION:								`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/action`,
	ACTION_RECORD:				`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/action/:action`,
	ACTION_RECORD_ACTION:	`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/action/:action/:recordID`,
	PARSE_WIKI:        		`${storesRoute}/:appID/:slug/:menuID/:moduleID/:from/wiki`,
	EDIT_WIKI:      			`${storesRoute}/:appID/:slug/:menuID/:moduleID/:from/wiki/edit`,
	RECORD_PARSE_WIKI:  	`${storesRoute}/:appID/:slug/:menuID/:moduleID/record/:action/:recordID/:from/wiki`,
	RECORD_EDIT_WIKI:  		`${storesRoute}/:appID/:slug/:menuID/:moduleID/record/:action/:recordID/:from/wiki/edit`,
  LIQUID_TEMPLATE_VIEW:	`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/liquidTemplateView/:recordID`,
  FILTER_RULES_VIEW:    `${storesRoute}/:appID/:slug/:menuID/:moduleID/views/filterRules`,
  FILTER_RULES_RECORD:	`${storesRoute}/:appID/:slug/:menuID/:moduleID/views/filterRules/:action`,
  FILTER_RULES_RECORD_ACTION: `${storesRoute}/:appID/:slug/:menuID/:moduleID/views/filterRules/:action/:recordID`,
  SINGLE_VIEW:					`/page/:slug/:appID/:moduleID/views/:viewID`,
};
/* eslint-enable */
